In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [4]:
df  = pd.read_csv(r"C:\Users\AM HK\Documents\hospital_analytics.csv")

In [5]:
df.head()

,Patient_ID,Patient_Name,Age,Gender,Department,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Treatment,Doctor,Hospital_Branch,Insurance_Type,Treatment_Cost,Length_of_Stay,Patient_Satisfaction,Outcome,Age_Group,Admission_Month,Admission_Month_Num,Admission_Week,Day_of_Week
0,P100001,Patient_100001,24,Female,Neurology,2026-06-14,2026-06-17,Emergency,Diabetes,Physiotherapy,Dr. Fatima,Islamabad,Self Pay,50322.48,3,3.9,Recovered,19-35,June,6,24,Sunday
1,P100002,Patient_100002,82,Female,Maternity,2026-06-15,2026-06-22,Emergency,Appendicitis,Observation,Dr. Imran,Lahore,Self Pay,56368.49,7,3.6,Improved,65+,June,6,25,Monday
2,P100003,Patient_100003,29,Male,Cardiology,2026-07-26,2026-07-28,Elective,Fracture,Observation,Dr. Usman,Islamabad,Private Insurance,30822.28,2,2.4,Recovered,19-35,July,7,30,Sunday
3,P100004,Patient_100004,33,Female,Emergency,2026-05-20,2026-05-24,Emergency,Routine Checkup,Medication,Dr. Usman,Lahore,Government Insurance,30709.16,4,3.8,Recovered,19-35,May,5,21,Wednesday
4,P100005,Patient_100005,26,Male,Oncology,2026-04-26,2026-04-30,Elective,Heart Disease,Medication,Dr. Fatima,Islamabad,Private Insurance,43911.01,4,5.0,Recovered,19-35,April,4,17,Sunday

In [6]:
df.info

<bound method DataFrame.info of      Patient_ID    Patient_Name  Age  Gender   Department Admission_Date  \
0       P100001  Patient_100001   24  Female    Neurology     2026-06-14
1       P100002  Patient_100002   82  Female    Maternity     2026-06-15
2       P100003  Patient_100003   29    Male   Cardiology     2026-07-26
3       P100004  Patient_100004   33  Female    Emergency     2026-05-20
4       P100005  Patient_100005   26    Male     Oncology     2026-04-26
...         ...             ...  ...     ...          ...            ...
4995    P104996  Patient_104996   50  Female    Maternity     2026-06-25
4996    P104997  Patient_104997   45  Female     Oncology     2026-08-03
4997    P104998  Patient_104998   41    Male   Cardiology     2026-05-06
4998    P104999  Patient_104999   42    Male  Orthopedics     2026-07-24
4999    P105000  Patient_105000   58    Male  Orthopedics     2026-05-31

     Discharge_Date Admission_Type              Diagnosis      Treatment  \
0        2026-06-17      Emergency               Diabetes  Physiotherapy
1        2026-06-22      Emergency           Appendicitis    Observation
2        2026-07-28       Elective               Fracture    Observation
3        2026-05-24      Emergency        Routine Checkup     Medication
4        2026-04-30       Elective          Heart Disease     Medication
...             ...            ...                    ...            ...
4995     2026-06-28      Emergency  Respiratory Infection    Observation
4996     2026-08-05      Emergency                 Cancer     Medication
4997     2026-05-09         Urgent           Appendicitis     Medication
4998     2026-07-26       Elective        Routine Checkup     Medication
4999     2026-06-06       Elective                 Cancer        Surgery

          Doctor Hospital_Branch        Insurance_Type  Treatment_Cost  \
0     Dr. Fatima       Islamabad              Self Pay        50322.48
1      Dr. Imran          Lahore              Self Pay        56368.49
2      Dr. Usman       Islamabad     Private Insurance        30822.28
3      Dr. Usman          Lahore  Government Insurance        30709.16
4     Dr. Fatima       Islamabad     Private Insurance        43911.01
...          ...             ...                   ...             ...
4995  Dr. Ayesha       Islamabad              Self Pay        33902.05
4996   Dr. Bilal       Islamabad              Self Pay        36255.42
4997    Dr. Sana      Rawalpindi     Private Insurance        43300.85
4998  Dr. Fatima         Karachi              Self Pay        26535.95
4999    Dr. Sana       Islamabad     Private Insurance       224902.54

      Length_of_Stay  Patient_Satisfaction    Outcome Age_Group  \
0                  3                   3.9  Recovered     19-35
1                  7                   3.6   Improved       65+
2                  2                   2.4  Recovered     19-35
3                  4                   3.8  Recovered     19-35
4                  4                   5.0  Recovered     19-35
...              ...                   ...        ...       ...
4995               3                   4.6  Recovered     36-50
4996               2                   5.0   Improved     36-50
4997               3                   3.9   Improved     36-50
4998               2                   4.1  Recovered     36-50
4999               6                   4.0  Recovered     51-65

     Admission_Month  Admission_Month_Num  Admission_Week Day_of_Week
0               June                    6              24      Sunday
1               June                    6              25      Monday
2               July                    7              30      Sunday
3                May                    5              21   Wednesday
4              April                    4              17      Sunday
...              ...                  ...             ...         ...
4995            June                    6              26    Thursday
4996          August                    8              32      Monday
4997             May                    5              19   Wednesday
4998            July                    7              30      Friday
4999             May                    5              22      Sunday

[5000 rows x 22 columns]>

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.shape

(5000, 22)

In [17]:
df.isnull().sum()

Patient_ID               0
Patient_Name             0
Age                      0
Gender                   0
Department               0
Admission_Date           0
Discharge_Date           0
Admission_Type           0
Diagnosis                0
Treatment                0
Doctor                   0
Hospital_Branch          0
Insurance_Type          25
Treatment_Cost           0
Length_of_Stay           0
Patient_Satisfaction    25
Outcome                  0
Age_Group                0
Admission_Month          0
Admission_Month_Num      0
Admission_Week           0
Day_of_Week              0
dtype: int64

In [18]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

Patient_ID              0.0
Patient_Name            0.0
Age                     0.0
Gender                  0.0
Department              0.0
Admission_Date          0.0
Discharge_Date          0.0
Admission_Type          0.0
Diagnosis               0.0
Treatment               0.0
Doctor                  0.0
Hospital_Branch         0.0
Insurance_Type          0.5
Treatment_Cost          0.0
Length_of_Stay          0.0
Patient_Satisfaction    0.5
Outcome                 0.0
Age_Group               0.0
Admission_Month         0.0
Admission_Month_Num     0.0
Admission_Week          0.0
Day_of_Week             0.0
dtype: float64

In [19]:
missing_percentage = (
    df.isnull().sum()
    .div(len(df))
    .mul(100)
    .round(2)
)

missing_percentage

Patient_ID              0.0
Patient_Name            0.0
Age                     0.0
Gender                  0.0
Department              0.0
Admission_Date          0.0
Discharge_Date          0.0
Admission_Type          0.0
Diagnosis               0.0
Treatment               0.0
Doctor                  0.0
Hospital_Branch         0.0
Insurance_Type          0.5
Treatment_Cost          0.0
Length_of_Stay          0.0
Patient_Satisfaction    0.5
Outcome                 0.0
Age_Group               0.0
Admission_Month         0.0
Admission_Month_Num     0.0
Admission_Week          0.0
Day_of_Week             0.0
dtype: float64

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Patient_ID            5000 non-null   str
 1   Patient_Name          5000 non-null   str
 2   Age                   5000 non-null   int64
 3   Gender                5000 non-null   str
 4   Department            5000 non-null   str
 5   Admission_Date        5000 non-null   str
 6   Discharge_Date        5000 non-null   str
 7   Admission_Type        5000 non-null   str
 8   Diagnosis             5000 non-null   str
 9   Treatment             5000 non-null   str
 10  Doctor                5000 non-null   str
 11  Hospital_Branch       5000 non-null   str
 12  Insurance_Type        4975 non-null   str
 13  Treatment_Cost        5000 non-null   float64
 14  Length_of_Stay        5000 non-null   int64
 15  Patient_Satisfaction  4975 non-null   float64
 16  Outcome               5000 non-null   str
 17  Age_Group             5000 non-null   str
 18  Admission_Month       5000 non-null   str
 19  Admission_Month_Num   5000 non-null   int64
 20  Admission_Week        5000 non-null   int64
 21  Day_of_Week           5000 non-null   str
dtypes: float64(2), int64(4), str(16)
memory usage: 859.5 KB

In [22]:
df.dtypes

Patient_ID                  str
Patient_Name                str
Age                       int64
Gender                      str
Department                  str
Admission_Date              str
Discharge_Date              str
Admission_Type              str
Diagnosis                   str
Treatment                   str
Doctor                      str
Hospital_Branch             str
Insurance_Type              str
Treatment_Cost          float64
Length_of_Stay            int64
Patient_Satisfaction    float64
Outcome                     str
Age_Group                   str
Admission_Month             str
Admission_Month_Num       int64
Admission_Week            int64
Day_of_Week                 str
dtype: object

In [23]:
df.head(5)

,Patient_ID,Patient_Name,Age,Gender,Department,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Treatment,Doctor,Hospital_Branch,Insurance_Type,Treatment_Cost,Length_of_Stay,Patient_Satisfaction,Outcome,Age_Group,Admission_Month,Admission_Month_Num,Admission_Week,Day_of_Week
0,P100001,Patient_100001,24,Female,Neurology,2026-06-14,2026-06-17,Emergency,Diabetes,Physiotherapy,Dr. Fatima,Islamabad,Self Pay,50322.48,3,3.9,Recovered,19-35,June,6,24,Sunday
1,P100002,Patient_100002,82,Female,Maternity,2026-06-15,2026-06-22,Emergency,Appendicitis,Observation,Dr. Imran,Lahore,Self Pay,56368.49,7,3.6,Improved,65+,June,6,25,Monday
2,P100003,Patient_100003,29,Male,Cardiology,2026-07-26,2026-07-28,Elective,Fracture,Observation,Dr. Usman,Islamabad,Private Insurance,30822.28,2,2.4,Recovered,19-35,July,7,30,Sunday
3,P100004,Patient_100004,33,Female,Emergency,2026-05-20,2026-05-24,Emergency,Routine Checkup,Medication,Dr. Usman,Lahore,Government Insurance,30709.16,4,3.8,Recovered,19-35,May,5,21,Wednesday
4,P100005,Patient_100005,26,Male,Oncology,2026-04-26,2026-04-30,Elective,Heart Disease,Medication,Dr. Fatima,Islamabad,Private Insurance,43911.01,4,5.0,Recovered,19-35,April,4,17,Sunday

In [24]:
(df.isnull().sum() / len(df) * 100).round(2)

Patient_ID              0.0
Patient_Name            0.0
Age                     0.0
Gender                  0.0
Department              0.0
Admission_Date          0.0
Discharge_Date          0.0
Admission_Type          0.0
Diagnosis               0.0
Treatment               0.0
Doctor                  0.0
Hospital_Branch         0.0
Insurance_Type          0.5
Treatment_Cost          0.0
Length_of_Stay          0.0
Patient_Satisfaction    0.5
Outcome                 0.0
Age_Group               0.0
Admission_Month         0.0
Admission_Month_Num     0.0
Admission_Week          0.0
Day_of_Week             0.0
dtype: float64

In [25]:
df[df.isnull().any(axis=1)]

,Patient_ID,Patient_Name,Age,Gender,Department,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Treatment,Doctor,Hospital_Branch,Insurance_Type,Treatment_Cost,Length_of_Stay,Patient_Satisfaction,Outcome,Age_Group,Admission_Month,Admission_Month_Num,Admission_Week,Day_of_Week
6,P100007,Patient_100007,57,Female,Neurology,2026-07-20,2026-07-22,Emergency,Respiratory Infection,Surgery,Dr. Sana,Rawalpindi,NaN,146617.26,2,3.3,Critical,51-65,July,7,30,Monday
123,P100124,Patient_100124,79,Female,Maternity,2026-08-16,2026-08-18,Elective,Stroke,Surgery,Dr. Maryam,Islamabad,NaN,120827.67,2,3.6,Critical,65+,August,8,33,Sunday
152,P100153,Patient_100153,64,Female,General Medicine,2026-06-01,2026-06-08,Elective,Appendicitis,Physiotherapy,Dr. Zainab,Rawalpindi,Private Insurance,51055.90,7,NaN,Transferred,51-65,June,6,23,Monday
155,P100156,Patient_100156,74,Female,Oncology,2026-05-09,2026-05-13,Emergency,Respiratory Infection,Surgery,Dr. Fatima,Rawalpindi,Government Insurance,219798.42,4,NaN,Improved,65+,May,5,19,Saturday
243,P100244,Patient_100244,42,Male,Cardiology,2026-04-20,2026-04-25,Emergency,Hypertension,Surgery,Dr. Hassan,Rawalpindi,NaN,178363.02,5,3.1,Transferred,36-50,April,4,17,Monday
292,P100293,Patient_100293,51,Male,Cardiology,2026-05-27,2026-06-01,Elective,Respiratory Infection,Physiotherapy,Dr. Sana,Lahore,NaN,40629.43,5,4.3,Transferred,51-65,May,5,22,Wednesday
311,P100312,Patient_100312,69,Female,Orthopedics,2026-05-21,2026-05-23,Urgent,Fracture,Medication,Dr. Maryam,Islamabad,Corporate,34840.13,2,NaN,Improved,65+,May,5,21,Thursday
435,P100436,Patient_100436,71,Female,Pediatrics,2026-08-02,2026-08-13,Emergency,Respiratory Infection,Surgery,Dr. Ahmed,Karachi,Government Insurance,158360.52,11,NaN,Recovered,65+,August,8,31,Sunday
454,P100455,Patient_100455,60,Female,Oncology,2026-06-21,2026-06-29,Emergency,Routine Checkup,Observation,Dr. Ahmed,Karachi,Private Insurance,53785.14,8,NaN,Critical,51-65,June,6,25,Sunday
484,P100485,Patient_100485,73,Female,Emergency,2026-05-21,2026-05-22,Elective,Pregnancy,Physiotherapy,Dr. Ayesha,Karachi,NaN,33072.43,1,3.9,Recovered,65+,May,5,21,Thursday
524,P100525,Patient_100525,31,Male,Orthopedics,2026-04-16,2026-04-19,Elective,Hypertension,Surgery,Dr. Sana,Islamabad,Self Pay,148522.43,3,NaN,Transferred,19-35,April,4,16,Thursday
763,P100764,Patient_100764,42,Male,Pediatrics,2026-08-17,2026-08-20,Urgent,Cancer,Medication,Dr. Bilal,Islamabad,NaN,34395.50,3,4.9,Recovered,36-50,August,8,34,Monday
985,P100986,Patient_100986,63,Female,Surgery,2026-08-01,2026-08-06,Urgent,Respiratory Infection,Surgery,Dr. Imran,Rawalpindi,NaN,192319.73,5,3.2,Critical,51-65,August,8,31,Saturday
999,P101000,Patient_101000,9,Female,Cardiology,2026-06-09,2026-06-13,Emergency,Heart Disease,Delivery,Dr. Sana,Karachi,NaN,103785.39,4,3.6,Improved,0-18,June,6,24,Tuesday
1135,P101136,Patient_101136,58,Female,Cardiology,2026-08-02,2026-08-09,Emergency,Heart Disease,Surgery,Dr. Maryam,Islamabad,Government Insurance,197746.29,7,NaN,Recovered,51-65,August,8,31,Sunday
1179,P101180,Patient_101180,51,Female,Pediatrics,2026-08-09,2026-08-17,Emergency,Routine Checkup,Diagnostic Procedure,Dr. Fatima,Islamabad,NaN,61267.23,8,4.2,Improved,51-65,August,8,32,Sunday
1266,P101267,Patient_101267,48,Male,Oncology,2026-07-26,2026-07-29,Emergency,Respiratory Infection,Surgery,Dr. Sana,Islamabad,NaN,232650.22,3,2.9,Recovered,36-50,July,7,30,Sunday
1282,P101283,Patient_101283,21,Male,Pediatrics,2026-05-10,2026-05-12,Elective,Heart Disease,Physiotherapy,Dr. Ahmed,Rawalpindi,Corporate,26066.49,2,NaN,Recovered,19-35,May,5,19,Sunday
1385,P101386,Patient_101386,43,Male,Pediatrics,2026-04-09,2026-04-10,Elective,Fracture,Medication,Dr. Ayesha,Islamabad,NaN,19534.31,1,4.0,Transferred,36-50,April,4,15,Thursday
1494,P101495,Patient_101495,15,Female,Neurology,2026-05-30,2026-06-19,Emergency,Pregnancy,Medication,Dr. Maryam,Islamabad,NaN,120147.55,20,3.0,Improved,0-18,May,5,22,Saturday
1506,P101507,Patient_101507,59,Female,Maternity,2026-04-24,2026-04-27,Urgent,Heart Disease,Physiotherapy,Dr. Zainab,Islamabad,Private Insurance,46660.67,3,NaN,Recovered,51-65,April,4,17,Friday
1558,P101559,Patient_101559,90,Male,Oncology,2026-08-08,2026-08-11,Elective,Routine Checkup,Diagnostic Procedure,Dr. Ahmed,Karachi,Corporate,53725.64,3,NaN,Improved,65+,August,8,32,Saturday
1564,P101565,Patient_101565,38,Female,Cardiology,2026-08-10,2026-08-13,Urgent,Respiratory Infection,Observation,Dr. Bilal,Rawalpindi,Self Pay,45755.85,3,NaN,Improved,36-50,August,8,33,Monday
1650,P101651,Patient_101651,44,Female,Maternity,2026-05-16,2026-05-19,Emergency,Hypertension,Surgery,Dr. Ahmed,Islamabad,Private Insurance,126893.66,3,NaN,Improved,36-50,May,5,20,Saturday
1967,P101968,Patient_101968,81,Female,General Medicine,2026-05-16,2026-05-20,Elective,Pregnancy,Delivery,Dr. Zainab,Rawalpindi,Private Insurance,80503.15,4,NaN,Deceased,65+,May,5,20,Saturday
2307,P102308,Patient_102308,50,Female,Orthopedics,2026-05-02,2026-05-07,Emergency,Cancer,Delivery,Dr. Bilal,Lahore,Self Pay,86442.38,5,NaN,Recovered,36-50,May,5,18,Saturday
2340,P102341,Patient_102341,40,Female,General Medicine,2026-06-23,2026-06-27,Emergency,Respiratory Infection,Medication,Dr. Maryam,Karachi,Government Insurance,38990.55,4,NaN,Recovered,36-50,June,6,26,Tuesday
2355,P102356,Patient_102356,48,Female,Pediatrics,2026-05-29,2026-06-07,Emergency,Diabetes,Medication,Dr. Hassan,Lahore,Government Insurance,44219.59,9,NaN,Recovered,36-50,May,5,22,Friday
2442,P102443,Patient_102443,43,Male,General Medicine,2026-06-13,2026-06-14,Urgent,Stroke,Medication,Dr. Maryam,Lahore,Self Pay,20856.63,1,NaN,Recovered,36-50,June,6,24,Saturday
2461,P102462,Patient_102462,66,Female,Surgery,2026-06-21,2026-06-27,Emergency,Hypertension,Medication,Dr. Bilal,Karachi,NaN,38611.98,6,3.4,Recovered,65+,June,6,25,Sunday
2528,P102529,Patient_102529,51,Female,Pediatrics,2026-04-15,2026-04-22,Emergency,Heart Disease,Medication,Dr. Hassan,Karachi,NaN,43517.80,7,4.7,Improved,51-65,April,4,16,Wednesday
2583,P102584,Patient_102584,15,Female,Emergency,2026-04-12,2026-04-17,Elective,Respiratory Infection,Surgery,Dr. Ayesha,Lahore,NaN,179484.32,5,3.4,Recovered,0-18,April,4,15,Sunday
2611,P102612,Patient_102612,80,Female,Neurology,2026-04-06,2026-04-09,Emergency,Fracture,Physiotherapy,Dr. Imran,Rawalpindi,NaN,61415.40,3,3.7,Improved,65+,April,4,15,Monday
2787,P102788,Patient_102788,34,Female,General Medicine,2026-05-06,2026-05-16,Urgent,Hypertension,Surgery,Dr. Sana,Lahore,Private Insurance,147814.03,10,NaN,Transferred,19-35,May,5,19,Wednesday
2821,P102822,Patient_102822,45,Male,Pediatrics,2026-06-01,2026-06-03,Urgent,Appendicitis,Delivery,Dr. Ayesha,Lahore,NaN,56152.54,2,4.3,Improved,36-50,June,6,23,Monday
3132,P103133,Patient_103133,18,Female,Pediatrics,2026-08-13,2026-08-18,Emergency,Cancer,Delivery,Dr. Bilal,Islamabad,Private Insurance,72079.44,5,NaN,Critical,0-18,August,8,33,Thursday
3144,P103145,Patient_103145,15,Female,Emergency,2026-04-21,2026-04-24,Urgent,Pregnancy,Physiotherapy,Dr. Sana,Rawalpindi,NaN,50660.56,3,4.6,Recovered,0-18,April,4,17,Tuesday
3194,P103195,Patient_103195,89,Female,Cardiology,2026-07-06,2026-07-11,Emergency,Cancer,Diagnostic Procedure,Dr. Usman,Lahore,Corporate,97926.85,5,NaN,Improved,65+,July,7,28,Monday
3257,P103258,Patient_103258,41,Female,Maternity,2026-08-17,2026-08-21,Emergency,Respiratory Infection,Medication,Dr. Sana,Islamabad,Private Insurance,35480.83,4,NaN,Recovered,36-50,August,8,34,Monday
3294,P103295,Patient_103295,47,Female,Emergency,2026-05-27,2026-05-31,Urgent,Heart Disease,Physiotherapy,Dr. Sana,Rawalpindi,NaN,45296.09,4,2.0,Recovered,36-50,May,5,22,Wednesday
3333,P103334,Patient_103334,58,Female,Emergency,2026-06-24,2026-06-26,Urgent,Fracture,Medication,Dr. Fatima,Lahore,NaN,37796.40,2,3.9,Recovered,51-65,June,6,26,Wednesday
3337,P103338,Patient_103338,28,Male,Emergency,2026-06-05,2026-06-09,Emergency,Appendicitis,Delivery,Dr. Ahmed,Islamabad,NaN,91229.47,4,5.0,Recovered,19-35,June,6,23,Friday
3434,P103435,Patient_103435,64,Female,Oncology,2026-05-05,2026-05-07,Urgent,Fracture,Observation,Dr. Imran,Karachi,Corporate,33170.77,2,NaN,Recovered,51-65,May,5,19,Tuesday
3501,P103502,Patient_103502,61,Male,Pediatrics,2026-04-04,2026-04-10,Emergency,Heart Disease,Diagnostic Procedure,Dr. Hassan,Karachi,Government Insurance,69726.40,6,NaN,Recovered,51-65,April,4,14,Saturday
3783,P103784,Patient_103784,46,Male,Emergency,2026-07-04,2026-07-04,Urgent,Pregnancy,Diagnostic Procedure,Dr. Maryam,Rawalpindi,NaN,35356.87,0,4.5,Recovered,36-50,July,7,27,Saturday
3909,P103910,Patient_103910,60,Male,Pediatrics,2026-07-25,2026-07-27,Urgent,Respiratory Infection,Diagnostic Procedure,Dr. Ahmed,Islamabad,NaN,39721.35,2,3.8,Improved,51-65,July,7,30,Saturday
3996,P103997,Patient_103997,30,Male,Neurology,2026-04-04,2026-04-09,Elective,Routine Checkup,Surgery,Dr. Ayesha,Islamabad,NaN,185595.56,5,4.4,Recovered,19-35,April,4,14,Saturday
4063,P104064,Patient_104064,71,Female,General Medicine,2026-07-06,2026-07-13,Elective,Diabetes,Medication,Dr. Imran,Lahore,NaN,58181.73,7,4.9,Recovered,65+,July,7,28,Monday
4610,P104611,Patient_104611,72,Female,Surgery,2026-08-14,2026-08-17,Urgent,Diabetes,Medication,Dr. Imran,Rawalpindi,Private Insurance,40766.28,3,NaN,Recovered,65+,August,8,33,Friday
4903,P104904,Patient_104904,64,Female,Oncology,2026-04-12,2026-04-14,Elective,Fracture,Diagnostic Procedure,Dr. Maryam,Islamabad,Corporate,55018.01,2,NaN,Recovered,51-65,April,4,15,Sunday

In [26]:
df.isnull().sum()

Patient_ID               0
Patient_Name             0
Age                      0
Gender                   0
Department               0
Admission_Date           0
Discharge_Date           0
Admission_Type           0
Diagnosis                0
Treatment                0
Doctor                   0
Hospital_Branch          0
Insurance_Type          25
Treatment_Cost           0
Length_of_Stay           0
Patient_Satisfaction    25
Outcome                  0
Age_Group                0
Admission_Month          0
Admission_Month_Num      0
Admission_Week           0
Day_of_Week              0
dtype: int64

In [27]:
(df.isnull().sum() / len(df) * 100).round(2)

Patient_ID              0.0
Patient_Name            0.0
Age                     0.0
Gender                  0.0
Department              0.0
Admission_Date          0.0
Discharge_Date          0.0
Admission_Type          0.0
Diagnosis               0.0
Treatment               0.0
Doctor                  0.0
Hospital_Branch         0.0
Insurance_Type          0.5
Treatment_Cost          0.0
Length_of_Stay          0.0
Patient_Satisfaction    0.5
Outcome                 0.0
Age_Group               0.0
Admission_Month         0.0
Admission_Month_Num     0.0
Admission_Week          0.0
Day_of_Week             0.0
dtype: float64

In [28]:
df[df.isnull().any(axis=1)]

,Patient_ID,Patient_Name,Age,Gender,Department,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Treatment,Doctor,Hospital_Branch,Insurance_Type,Treatment_Cost,Length_of_Stay,Patient_Satisfaction,Outcome,Age_Group,Admission_Month,Admission_Month_Num,Admission_Week,Day_of_Week
6,P100007,Patient_100007,57,Female,Neurology,2026-07-20,2026-07-22,Emergency,Respiratory Infection,Surgery,Dr. Sana,Rawalpindi,NaN,146617.26,2,3.3,Critical,51-65,July,7,30,Monday
123,P100124,Patient_100124,79,Female,Maternity,2026-08-16,2026-08-18,Elective,Stroke,Surgery,Dr. Maryam,Islamabad,NaN,120827.67,2,3.6,Critical,65+,August,8,33,Sunday
152,P100153,Patient_100153,64,Female,General Medicine,2026-06-01,2026-06-08,Elective,Appendicitis,Physiotherapy,Dr. Zainab,Rawalpindi,Private Insurance,51055.90,7,NaN,Transferred,51-65,June,6,23,Monday
155,P100156,Patient_100156,74,Female,Oncology,2026-05-09,2026-05-13,Emergency,Respiratory Infection,Surgery,Dr. Fatima,Rawalpindi,Government Insurance,219798.42,4,NaN,Improved,65+,May,5,19,Saturday
243,P100244,Patient_100244,42,Male,Cardiology,2026-04-20,2026-04-25,Emergency,Hypertension,Surgery,Dr. Hassan,Rawalpindi,NaN,178363.02,5,3.1,Transferred,36-50,April,4,17,Monday
292,P100293,Patient_100293,51,Male,Cardiology,2026-05-27,2026-06-01,Elective,Respiratory Infection,Physiotherapy,Dr. Sana,Lahore,NaN,40629.43,5,4.3,Transferred,51-65,May,5,22,Wednesday
311,P100312,Patient_100312,69,Female,Orthopedics,2026-05-21,2026-05-23,Urgent,Fracture,Medication,Dr. Maryam,Islamabad,Corporate,34840.13,2,NaN,Improved,65+,May,5,21,Thursday
435,P100436,Patient_100436,71,Female,Pediatrics,2026-08-02,2026-08-13,Emergency,Respiratory Infection,Surgery,Dr. Ahmed,Karachi,Government Insurance,158360.52,11,NaN,Recovered,65+,August,8,31,Sunday
454,P100455,Patient_100455,60,Female,Oncology,2026-06-21,2026-06-29,Emergency,Routine Checkup,Observation,Dr. Ahmed,Karachi,Private Insurance,53785.14,8,NaN,Critical,51-65,June,6,25,Sunday
484,P100485,Patient_100485,73,Female,Emergency,2026-05-21,2026-05-22,Elective,Pregnancy,Physiotherapy,Dr. Ayesha,Karachi,NaN,33072.43,1,3.9,Recovered,65+,May,5,21,Thursday
524,P100525,Patient_100525,31,Male,Orthopedics,2026-04-16,2026-04-19,Elective,Hypertension,Surgery,Dr. Sana,Islamabad,Self Pay,148522.43,3,NaN,Transferred,19-35,April,4,16,Thursday
763,P100764,Patient_100764,42,Male,Pediatrics,2026-08-17,2026-08-20,Urgent,Cancer,Medication,Dr. Bilal,Islamabad,NaN,34395.50,3,4.9,Recovered,36-50,August,8,34,Monday
985,P100986,Patient_100986,63,Female,Surgery,2026-08-01,2026-08-06,Urgent,Respiratory Infection,Surgery,Dr. Imran,Rawalpindi,NaN,192319.73,5,3.2,Critical,51-65,August,8,31,Saturday
999,P101000,Patient_101000,9,Female,Cardiology,2026-06-09,2026-06-13,Emergency,Heart Disease,Delivery,Dr. Sana,Karachi,NaN,103785.39,4,3.6,Improved,0-18,June,6,24,Tuesday
1135,P101136,Patient_101136,58,Female,Cardiology,2026-08-02,2026-08-09,Emergency,Heart Disease,Surgery,Dr. Maryam,Islamabad,Government Insurance,197746.29,7,NaN,Recovered,51-65,August,8,31,Sunday
1179,P101180,Patient_101180,51,Female,Pediatrics,2026-08-09,2026-08-17,Emergency,Routine Checkup,Diagnostic Procedure,Dr. Fatima,Islamabad,NaN,61267.23,8,4.2,Improved,51-65,August,8,32,Sunday
1266,P101267,Patient_101267,48,Male,Oncology,2026-07-26,2026-07-29,Emergency,Respiratory Infection,Surgery,Dr. Sana,Islamabad,NaN,232650.22,3,2.9,Recovered,36-50,July,7,30,Sunday
1282,P101283,Patient_101283,21,Male,Pediatrics,2026-05-10,2026-05-12,Elective,Heart Disease,Physiotherapy,Dr. Ahmed,Rawalpindi,Corporate,26066.49,2,NaN,Recovered,19-35,May,5,19,Sunday
1385,P101386,Patient_101386,43,Male,Pediatrics,2026-04-09,2026-04-10,Elective,Fracture,Medication,Dr. Ayesha,Islamabad,NaN,19534.31,1,4.0,Transferred,36-50,April,4,15,Thursday
1494,P101495,Patient_101495,15,Female,Neurology,2026-05-30,2026-06-19,Emergency,Pregnancy,Medication,Dr. Maryam,Islamabad,NaN,120147.55,20,3.0,Improved,0-18,May,5,22,Saturday
1506,P101507,Patient_101507,59,Female,Maternity,2026-04-24,2026-04-27,Urgent,Heart Disease,Physiotherapy,Dr. Zainab,Islamabad,Private Insurance,46660.67,3,NaN,Recovered,51-65,April,4,17,Friday
1558,P101559,Patient_101559,90,Male,Oncology,2026-08-08,2026-08-11,Elective,Routine Checkup,Diagnostic Procedure,Dr. Ahmed,Karachi,Corporate,53725.64,3,NaN,Improved,65+,August,8,32,Saturday
1564,P101565,Patient_101565,38,Female,Cardiology,2026-08-10,2026-08-13,Urgent,Respiratory Infection,Observation,Dr. Bilal,Rawalpindi,Self Pay,45755.85,3,NaN,Improved,36-50,August,8,33,Monday
1650,P101651,Patient_101651,44,Female,Maternity,2026-05-16,2026-05-19,Emergency,Hypertension,Surgery,Dr. Ahmed,Islamabad,Private Insurance,126893.66,3,NaN,Improved,36-50,May,5,20,Saturday
1967,P101968,Patient_101968,81,Female,General Medicine,2026-05-16,2026-05-20,Elective,Pregnancy,Delivery,Dr. Zainab,Rawalpindi,Private Insurance,80503.15,4,NaN,Deceased,65+,May,5,20,Saturday
2307,P102308,Patient_102308,50,Female,Orthopedics,2026-05-02,2026-05-07,Emergency,Cancer,Delivery,Dr. Bilal,Lahore,Self Pay,86442.38,5,NaN,Recovered,36-50,May,5,18,Saturday
2340,P102341,Patient_102341,40,Female,General Medicine,2026-06-23,2026-06-27,Emergency,Respiratory Infection,Medication,Dr. Maryam,Karachi,Government Insurance,38990.55,4,NaN,Recovered,36-50,June,6,26,Tuesday
2355,P102356,Patient_102356,48,Female,Pediatrics,2026-05-29,2026-06-07,Emergency,Diabetes,Medication,Dr. Hassan,Lahore,Government Insurance,44219.59,9,NaN,Recovered,36-50,May,5,22,Friday
2442,P102443,Patient_102443,43,Male,General Medicine,2026-06-13,2026-06-14,Urgent,Stroke,Medication,Dr. Maryam,Lahore,Self Pay,20856.63,1,NaN,Recovered,36-50,June,6,24,Saturday
2461,P102462,Patient_102462,66,Female,Surgery,2026-06-21,2026-06-27,Emergency,Hypertension,Medication,Dr. Bilal,Karachi,NaN,38611.98,6,3.4,Recovered,65+,June,6,25,Sunday
2528,P102529,Patient_102529,51,Female,Pediatrics,2026-04-15,2026-04-22,Emergency,Heart Disease,Medication,Dr. Hassan,Karachi,NaN,43517.80,7,4.7,Improved,51-65,April,4,16,Wednesday
2583,P102584,Patient_102584,15,Female,Emergency,2026-04-12,2026-04-17,Elective,Respiratory Infection,Surgery,Dr. Ayesha,Lahore,NaN,179484.32,5,3.4,Recovered,0-18,April,4,15,Sunday
2611,P102612,Patient_102612,80,Female,Neurology,2026-04-06,2026-04-09,Emergency,Fracture,Physiotherapy,Dr. Imran,Rawalpindi,NaN,61415.40,3,3.7,Improved,65+,April,4,15,Monday
2787,P102788,Patient_102788,34,Female,General Medicine,2026-05-06,2026-05-16,Urgent,Hypertension,Surgery,Dr. Sana,Lahore,Private Insurance,147814.03,10,NaN,Transferred,19-35,May,5,19,Wednesday
2821,P102822,Patient_102822,45,Male,Pediatrics,2026-06-01,2026-06-03,Urgent,Appendicitis,Delivery,Dr. Ayesha,Lahore,NaN,56152.54,2,4.3,Improved,36-50,June,6,23,Monday
3132,P103133,Patient_103133,18,Female,Pediatrics,2026-08-13,2026-08-18,Emergency,Cancer,Delivery,Dr. Bilal,Islamabad,Private Insurance,72079.44,5,NaN,Critical,0-18,August,8,33,Thursday
3144,P103145,Patient_103145,15,Female,Emergency,2026-04-21,2026-04-24,Urgent,Pregnancy,Physiotherapy,Dr. Sana,Rawalpindi,NaN,50660.56,3,4.6,Recovered,0-18,April,4,17,Tuesday
3194,P103195,Patient_103195,89,Female,Cardiology,2026-07-06,2026-07-11,Emergency,Cancer,Diagnostic Procedure,Dr. Usman,Lahore,Corporate,97926.85,5,NaN,Improved,65+,July,7,28,Monday
3257,P103258,Patient_103258,41,Female,Maternity,2026-08-17,2026-08-21,Emergency,Respiratory Infection,Medication,Dr. Sana,Islamabad,Private Insurance,35480.83,4,NaN,Recovered,36-50,August,8,34,Monday
3294,P103295,Patient_103295,47,Female,Emergency,2026-05-27,2026-05-31,Urgent,Heart Disease,Physiotherapy,Dr. Sana,Rawalpindi,NaN,45296.09,4,2.0,Recovered,36-50,May,5,22,Wednesday
3333,P103334,Patient_103334,58,Female,Emergency,2026-06-24,2026-06-26,Urgent,Fracture,Medication,Dr. Fatima,Lahore,NaN,37796.40,2,3.9,Recovered,51-65,June,6,26,Wednesday
3337,P103338,Patient_103338,28,Male,Emergency,2026-06-05,2026-06-09,Emergency,Appendicitis,Delivery,Dr. Ahmed,Islamabad,NaN,91229.47,4,5.0,Recovered,19-35,June,6,23,Friday
3434,P103435,Patient_103435,64,Female,Oncology,2026-05-05,2026-05-07,Urgent,Fracture,Observation,Dr. Imran,Karachi,Corporate,33170.77,2,NaN,Recovered,51-65,May,5,19,Tuesday
3501,P103502,Patient_103502,61,Male,Pediatrics,2026-04-04,2026-04-10,Emergency,Heart Disease,Diagnostic Procedure,Dr. Hassan,Karachi,Government Insurance,69726.40,6,NaN,Recovered,51-65,April,4,14,Saturday
3783,P103784,Patient_103784,46,Male,Emergency,2026-07-04,2026-07-04,Urgent,Pregnancy,Diagnostic Procedure,Dr. Maryam,Rawalpindi,NaN,35356.87,0,4.5,Recovered,36-50,July,7,27,Saturday
3909,P103910,Patient_103910,60,Male,Pediatrics,2026-07-25,2026-07-27,Urgent,Respiratory Infection,Diagnostic Procedure,Dr. Ahmed,Islamabad,NaN,39721.35,2,3.8,Improved,51-65,July,7,30,Saturday
3996,P103997,Patient_103997,30,Male,Neurology,2026-04-04,2026-04-09,Elective,Routine Checkup,Surgery,Dr. Ayesha,Islamabad,NaN,185595.56,5,4.4,Recovered,19-35,April,4,14,Saturday
4063,P104064,Patient_104064,71,Female,General Medicine,2026-07-06,2026-07-13,Elective,Diabetes,Medication,Dr. Imran,Lahore,NaN,58181.73,7,4.9,Recovered,65+,July,7,28,Monday
4610,P104611,Patient_104611,72,Female,Surgery,2026-08-14,2026-08-17,Urgent,Diabetes,Medication,Dr. Imran,Rawalpindi,Private Insurance,40766.28,3,NaN,Recovered,65+,August,8,33,Friday
4903,P104904,Patient_104904,64,Female,Oncology,2026-04-12,2026-04-14,Elective,Fracture,Diagnostic Procedure,Dr. Maryam,Islamabad,Corporate,55018.01,2,NaN,Recovered,51-65,April,4,15,Sunday

In [29]:
df["Insurance_Type"] = df["Insurance_Type"].fillna("Unknown")

In [30]:
df["Insurance_Type"].isnull().sum()

np.int64(0)

In [31]:
df["Patient_Satisfaction"].median()

np.float64(3.9)

In [32]:
df["Patient_Satisfaction"] = df["Patient_Satisfaction"].fillna(
    df["Patient_Satisfaction"].median()
)

In [33]:
df["Patient_Satisfaction"].isnull().sum()

np.int64(0)

In [34]:
df.isnull().sum()

Patient_ID              0
Patient_Name            0
Age                     0
Gender                  0
Department              0
Admission_Date          0
Discharge_Date          0
Admission_Type          0
Diagnosis               0
Treatment               0
Doctor                  0
Hospital_Branch         0
Insurance_Type          0
Treatment_Cost          0
Length_of_Stay          0
Patient_Satisfaction    0
Outcome                 0
Age_Group               0
Admission_Month         0
Admission_Month_Num     0
Admission_Week          0
Day_of_Week             0
dtype: int64

In [35]:
df["Age"].min()

np.int64(1)

In [36]:
df["Age"].max()

np.int64(90)

In [37]:
df["Age"].describe()

count    5000.000000
mean       45.924000
std        19.498602
min         1.000000
25%        32.000000
50%        46.000000
75%        59.000000
max        90.000000
Name: Age, dtype: float64

In [38]:
df[(df["Age"] < 0) | (df["Age"] > 100)]

Empty DataFrame
Columns: [Patient_ID, Patient_Name, Age, Gender, Department, Admission_Date, Discharge_Date, Admission_Type, Diagnosis, Treatment, Doctor, Hospital_Branch, Insurance_Type, Treatment_Cost, Length_of_Stay, Patient_Satisfaction, Outcome, Age_Group, Admission_Month, Admission_Month_Num, Admission_Week, Day_of_Week]
Index: []

In [40]:
df["Gender"].value_counts()

Gender
Male      2688
Female    2312
Name: count, dtype: int64

In [41]:
df["Gender"].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [42]:
df["Department"].value_counts()

Department
Emergency           863
General Medicine    798
Pediatrics          618
Cardiology          562
Orthopedics         499
Surgery             491
Maternity           447
Neurology           408
Oncology            314
Name: count, dtype: int64

In [43]:
df["Doctor"].value_counts()

Doctor
Dr. Imran     543
Dr. Usman     521
Dr. Sana      518
Dr. Bilal     499
Dr. Fatima    498
Dr. Ayesha    495
Dr. Maryam    492
Dr. Hassan    487
Dr. Ahmed     483
Dr. Zainab    464
Name: count, dtype: int64

In [44]:
df[
    (df["Patient_Satisfaction"] < 1) |
    (df["Patient_Satisfaction"] > 5)
]

Empty DataFrame
Columns: [Patient_ID, Patient_Name, Age, Gender, Department, Admission_Date, Discharge_Date, Admission_Type, Diagnosis, Treatment, Doctor, Hospital_Branch, Insurance_Type, Treatment_Cost, Length_of_Stay, Patient_Satisfaction, Outcome, Age_Group, Admission_Month, Admission_Month_Num, Admission_Week, Day_of_Week]
Index: []

In [45]:
df[(df["Age"] < 0) | (df["Age"] > 100)]

Empty DataFrame
Columns: [Patient_ID, Patient_Name, Age, Gender, Department, Admission_Date, Discharge_Date, Admission_Type, Diagnosis, Treatment, Doctor, Hospital_Branch, Insurance_Type, Treatment_Cost, Length_of_Stay, Patient_Satisfaction, Outcome, Age_Group, Admission_Month, Admission_Month_Num, Admission_Week, Day_of_Week]
Index: []

In [46]:
df["Treatment_Cost"].value_counts()

Treatment_Cost
59967.13     2
18736.66     2
50322.48     1
56368.49     1
30822.28     1
            ..
33902.05     1
36255.42     1
43300.85     1
26535.95     1
224902.54    1
Name: count, Length: 4998, dtype: int64

In [47]:
 df[df["Treatment_Cost"] <= 0]

Empty DataFrame
Columns: [Patient_ID, Patient_Name, Age, Gender, Department, Admission_Date, Discharge_Date, Admission_Type, Diagnosis, Treatment, Doctor, Hospital_Branch, Insurance_Type, Treatment_Cost, Length_of_Stay, Patient_Satisfaction, Outcome, Age_Group, Admission_Month, Admission_Month_Num, Admission_Week, Day_of_Week]
Index: []

In [48]:
df[df["Treatment_Cost"] <= 0].shape

(0, 22)

In [49]:
df.nlargest(10, "Treatment_Cost")[
    ["Patient_ID", "Department", "Treatment", "Treatment_Cost"]
]

     Patient_ID   Department     Treatment  Treatment_Cost
2924    P102925   Cardiology       Surgery       264100.49
3040    P103041   Cardiology       Surgery       258721.69
3999    P104000      Surgery       Surgery       257000.04
4851    P104852   Cardiology       Surgery       252254.17
2073    P102074     Oncology       Surgery       251840.06
598     P100599      Surgery       Surgery       247283.63
1290    P101291  Orthopedics       Surgery       245659.50
219     P100220    Neurology  Chemotherapy       243069.83
1210    P101211    Neurology       Surgery       242720.90
733     P100734     Oncology       Surgery       240870.99

In [50]:
df["Length_of_Stay"].describe()

count    5000.000000
mean        4.371600
std         2.744781
min         0.000000
25%         2.000000
50%         4.000000
75%         6.000000
max        22.000000
Name: Length_of_Stay, dtype: float64

In [51]:
df[df["Length_of_Stay"] < 0]

Empty DataFrame
Columns: [Patient_ID, Patient_Name, Age, Gender, Department, Admission_Date, Discharge_Date, Admission_Type, Diagnosis, Treatment, Doctor, Hospital_Branch, Insurance_Type, Treatment_Cost, Length_of_Stay, Patient_Satisfaction, Outcome, Age_Group, Admission_Month, Admission_Month_Num, Admission_Week, Day_of_Week]
Index: []

In [52]:
df.nlargest(10, "Length_of_Stay")[
    ["Patient_ID", "Department", "Admission_Date",
     "Discharge_Date", "Length_of_Stay"]
]

     Patient_ID  Department Admission_Date Discharge_Date  Length_of_Stay
219     P100220   Neurology     2026-04-03     2026-04-25              22
1979    P101980  Pediatrics     2026-04-26     2026-05-18              22
678     P100679   Neurology     2026-08-02     2026-08-23              21
581     P100582  Pediatrics     2026-05-29     2026-06-18              20
1494    P101495   Neurology     2026-05-30     2026-06-19              20
2008    P102009  Pediatrics     2026-08-10     2026-08-30              20
279     P100280  Pediatrics     2026-05-11     2026-05-30              19
1987    P101988   Neurology     2026-07-23     2026-08-11              19
96      P100097   Emergency     2026-04-21     2026-05-09              18
668     P100669   Neurology     2026-07-15     2026-08-01              17

In [53]:
df[df["Discharge_Date"] < df["Admission_Date"]]

Empty DataFrame
Columns: [Patient_ID, Patient_Name, Age, Gender, Department, Admission_Date, Discharge_Date, Admission_Type, Diagnosis, Treatment, Doctor, Hospital_Branch, Insurance_Type, Treatment_Cost, Length_of_Stay, Patient_Satisfaction, Outcome, Age_Group, Admission_Month, Admission_Month_Num, Admission_Week, Day_of_Week]
Index: []

In [55]:
df[["Admission_Date", "Discharge_Date"]].dtypes

Admission_Date    str
Discharge_Date    str
dtype: object

In [56]:
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"])
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"])

In [57]:
calculated_stay = (
    df["Discharge_Date"] - df["Admission_Date"]
).dt.days

In [58]:
(df["Length_of_Stay"] != calculated_stay).sum()

np.int64(0)

In [59]:
Length_of_Stay = 22

In [60]:
df["Department"].value_counts()

Department
Emergency           863
General Medicine    798
Pediatrics          618
Cardiology          562
Orthopedics         499
Surgery             491
Maternity           447
Neurology           408
Oncology            314
Name: count, dtype: int64

In [61]:
department_analysis = (
    df["Department"]
    .value_counts()
    .reset_index()
)

department_analysis.columns = ["Department", "Patient_Count"]

department_analysis

         Department  Patient_Count
0         Emergency            863
1  General Medicine            798
2        Pediatrics            618
3        Cardiology            562
4       Orthopedics            499
5           Surgery            491
6         Maternity            447
7         Neurology            408
8          Oncology            314

In [62]:
df["Department"].value_counts()

Department
Emergency           863
General Medicine    798
Pediatrics          618
Cardiology          562
Orthopedics         499
Surgery             491
Maternity           447
Neurology           408
Oncology            314
Name: count, dtype: int64

In [63]:
department_analysis = (
    df["Department"]
    .value_counts()
    .reset_index()
)

In [64]:
department_analysis.columns = [
    "Department",
    "Patient_Count"
]

In [65]:
department_analysis

         Department  Patient_Count
0         Emergency            863
1  General Medicine            798
2        Pediatrics            618
3        Cardiology            562
4       Orthopedics            499
5           Surgery            491
6         Maternity            447
7         Neurology            408
8          Oncology            314

In [66]:
department_analysis["Percentage"] = (
    department_analysis["Patient_Count"]
    / len(df) * 100
).round(2)

In [67]:
department_analysis

         Department  Patient_Count  Percentage
0         Emergency            863       17.26
1  General Medicine            798       15.96
2        Pediatrics            618       12.36
3        Cardiology            562       11.24
4       Orthopedics            499        9.98
5           Surgery            491        9.82
6         Maternity            447        8.94
7         Neurology            408        8.16
8          Oncology            314        6.28

In [71]:
df["Admission_Type"].value_counts()

Admission_Type
Emergency    1925
Elective     1815
Urgent       1260
Name: count, dtype: int64

In [72]:
admission_analysis = (
    df["Admission_Type"]
    .value_counts()
    .reset_index()
)

admission_analysis.columns = [
    "Admission_Type",
    "Patient_Count"
]

admission_analysis

  Admission_Type  Patient_Count
0      Emergency           1925
1       Elective           1815
2         Urgent           1260

In [73]:
admission_analysis["Percentage"] = (
    admission_analysis["Patient_Count"]
    / len(df) * 100
).round(2)

In [74]:
admission_analysis

  Admission_Type  Patient_Count  Percentage
0      Emergency           1925        38.5
1       Elective           1815        36.3
2         Urgent           1260        25.2

In [75]:
department_admission = pd.crosstab(
    df["Department"],
    df["Admission_Type"]
)

department_admission

Admission_Type    Elective  Emergency  Urgent
Department
Cardiology             196        228     138
Emergency              320        339     204
General Medicine       306        280     212
Maternity              158        162     127
Neurology              151        156     101
Oncology               113        121      80
Orthopedics            173        206     120
Pediatrics             230        238     150
Surgery                168        195     128

In [76]:
department_admission["Total"] = department_admission.sum(axis=1)

department_admission

Admission_Type    Elective  Emergency  Urgent  Total
Department
Cardiology             196        228     138    562
Emergency              320        339     204    863
General Medicine       306        280     212    798
Maternity              158        162     127    447
Neurology              151        156     101    408
Oncology               113        121      80    314
Orthopedics            173        206     120    499
Pediatrics             230        238     150    618
Surgery                168        195     128    491

In [77]:
department_admission = pd.crosstab(
    df["Department"],
    df["Admission_Type"]
)

department_admission["Total"] = department_admission.sum(axis=1)

department_admission

Admission_Type    Elective  Emergency  Urgent  Total
Department
Cardiology             196        228     138    562
Emergency              320        339     204    863
General Medicine       306        280     212    798
Maternity              158        162     127    447
Neurology              151        156     101    408
Oncology               113        121      80    314
Orthopedics            173        206     120    499
Pediatrics             230        238     150    618
Surgery                168        195     128    491

In [78]:
department_admission["Emergency_Rate"] = (
    department_admission["Emergency"]
    / department_admission["Total"]
    * 100
).round(2)

In [79]:
department_admission

Admission_Type    Elective  Emergency  Urgent  Total  Emergency_Rate
Department
Cardiology             196        228     138    562           40.57
Emergency              320        339     204    863           39.28
General Medicine       306        280     212    798           35.09
Maternity              158        162     127    447           36.24
Neurology              151        156     101    408           38.24
Oncology               113        121      80    314           38.54
Orthopedics            173        206     120    499           41.28
Pediatrics             230        238     150    618           38.51
Surgery                168        195     128    491           39.71

In [80]:
department_admission.sort_values(
    "Emergency_Rate",
    ascending=False
)

Admission_Type    Elective  Emergency  Urgent  Total  Emergency_Rate
Department
Orthopedics            173        206     120    499           41.28
Cardiology             196        228     138    562           40.57
Surgery                168        195     128    491           39.71
Emergency              320        339     204    863           39.28
Oncology               113        121      80    314           38.54
Pediatrics             230        238     150    618           38.51
Neurology              151        156     101    408           38.24
Maternity              158        162     127    447           36.24
General Medicine       306        280     212    798           35.09

In [81]:
diagnosis_analysis = (
    df["Diagnosis"]
    .value_counts()
    .reset_index()
)

diagnosis_analysis.columns = [
    "Diagnosis",
    "Patient_Count"
]

diagnosis_analysis

               Diagnosis  Patient_Count
0        Routine Checkup            676
1          Heart Disease            615
2           Hypertension            615
3  Respiratory Infection            586
4               Diabetes            550
5               Fracture            473
6              Pregnancy            436
7           Appendicitis            389
8                 Cancer            339
9                 Stroke            321

In [82]:
diagnosis_analysis["Percentage"] = (
    diagnosis_analysis["Patient_Count"]
    / len(df) * 100
).round(2)

In [83]:
diagnosis_analysis

               Diagnosis  Patient_Count  Percentage
0        Routine Checkup            676       13.52
1          Heart Disease            615       12.30
2           Hypertension            615       12.30
3  Respiratory Infection            586       11.72
4               Diabetes            550       11.00
5               Fracture            473        9.46
6              Pregnancy            436        8.72
7           Appendicitis            389        7.78
8                 Cancer            339        6.78
9                 Stroke            321        6.42

In [84]:
top_5_diagnoses = diagnosis_analysis.head(5)

top_5_diagnoses

               Diagnosis  Patient_Count  Percentage
0        Routine Checkup            676       13.52
1          Heart Disease            615       12.30
2           Hypertension            615       12.30
3  Respiratory Infection            586       11.72
4               Diabetes            550       11.00

In [85]:
diagnosis_analysis.tail(5)

      Diagnosis  Patient_Count  Percentage
5      Fracture            473        9.46
6     Pregnancy            436        8.72
7  Appendicitis            389        7.78
8        Cancer            339        6.78
9        Stroke            321        6.42

In [86]:
total_cost = df["Treatment_Cost"].sum()

total_cost

np.float64(354705476.40999997)

In [87]:
f"${total_cost:,.2f}"

'$354,705,476.41'

In [88]:
average_cost = df["Treatment_Cost"].mean()

average_cost

np.float64(70941.095282)

In [89]:
department_financial = (
    df.groupby("Department")["Treatment_Cost"]
    .agg(["sum", "mean", "count"])
    .reset_index()
)

In [90]:
department_financial

         Department          sum          mean  count
0        Cardiology  46428271.16  82612.582135    562
1         Emergency  62358852.05  72258.229490    863
2  General Medicine  47562489.98  59602.117769    798
3         Maternity  28806426.04  64443.906130    447
4         Neurology  31907815.62  78205.430441    408
5          Oncology  27143447.83  86444.101369    314
6       Orthopedics  34328862.78  68795.316192    499
7        Pediatrics  35932540.54  58143.269482    618
8           Surgery  40236770.41  81948.615906    491

In [94]:
treatment_financial = (
    df.groupby("Treatment")["Treatment_Cost"]
    .agg(["sum", "mean", "count"])
    .reset_index()
)

In [95]:
treatment_financial.columns = [
    "Treatment",
    "Total_Cost",
    "Average_Cost",
    "Patient_Count"
]

In [96]:
treatment_financial.sort_values(
    "Total_Cost",
    ascending=False
)

              Treatment    Total_Cost   Average_Cost  Patient_Count
6               Surgery  1.197130e+08  157517.165289            760
3            Medication  6.065160e+07   40007.651860           1516
2  Diagnostic Procedure  4.902907e+07   57276.953376            856
0          Chemotherapy  3.440453e+07  124654.097862            276
5         Physiotherapy  3.324889e+07   52360.463465            635
1              Delivery  3.078706e+07   90817.277021            339
4           Observation  2.687128e+07   43481.029547            618

In [98]:
department_financial = (
    df.groupby("Department")["Treatment_Cost"]
    .agg(["sum", "mean", "count"])
    .reset_index()
)

In [99]:
department_financial.columns = [
    "Department",
    "Total_Cost",
    "Average_Cost",
    "Patient_Count"
]

In [100]:
department_financial

         Department   Total_Cost  Average_Cost  Patient_Count
0        Cardiology  46428271.16  82612.582135            562
1         Emergency  62358852.05  72258.229490            863
2  General Medicine  47562489.98  59602.117769            798
3         Maternity  28806426.04  64443.906130            447
4         Neurology  31907815.62  78205.430441            408
5          Oncology  27143447.83  86444.101369            314
6       Orthopedics  34328862.78  68795.316192            499
7        Pediatrics  35932540.54  58143.269482            618
8           Surgery  40236770.41  81948.615906            491

In [101]:
department_financial = department_financial.sort_values(
    "Total_Cost",
    ascending=False
)

department_financial

         Department   Total_Cost  Average_Cost  Patient_Count
1         Emergency  62358852.05  72258.229490            863
2  General Medicine  47562489.98  59602.117769            798
0        Cardiology  46428271.16  82612.582135            562
8           Surgery  40236770.41  81948.615906            491
7        Pediatrics  35932540.54  58143.269482            618
6       Orthopedics  34328862.78  68795.316192            499
4         Neurology  31907815.62  78205.430441            408
3         Maternity  28806426.04  64443.906130            447
5          Oncology  27143447.83  86444.101369            314

In [102]:
department_financial.columns

Index(['Department', 'Total_Cost', 'Average_Cost', 'Patient_Count'], dtype='str')

In [103]:
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"])
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"])

In [104]:
dashboard_summary = df.copy()

In [105]:
dashboard_summary.to_csv(
    "Hospital_Dashboard_Cleaned.csv",
    index=False
)

In [106]:
import os
os.getcwd()

'C:\\Users\\AM HK'